const fs = require('fs');
const path = require('path');

const updateEnvFile = (ngrokUrl: string) => {
  // Remove any trailing "Attempting to get ngrok URL" text from the URL
  const cleanUrl = ngrokUrl.split('\n').pop()?.trim() || ngrokUrl;
  
  const envPath = path.join(__dirname, '../packages/frontend/.env.development');
  const envContent = `# Auto-generated by update-ngrok-urls.ts
VITE_API_URL=${cleanUrl}
VITE_ENABLE_TWITTER=true
VITE_TWITTER_CALLBACK_URL=${cleanUrl}/api/twitter/callback
`;

  fs.writeFileSync(envPath, envContent);
  console.log(`✅ Updated ${envPath} with ngrok URL: ${cleanUrl}`);
  console.log('\n⚠️  Remember to update Twitter Developer Portal:');
  console.log(`1. Website URL: ${cleanUrl}`);
  console.log(`2. Callback URL: ${cleanUrl}/api/twitter/callback`);
};

// Get ngrok URL from command line argument
const ngrokUrl = process.argv[2];
if (!ngrokUrl) {
  console.error('❌ Please provide the ngrok URL as an argument');
  process.exit(1);
}

updateEnvFile(ngrokUrl); 